version: '3'
services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
  api:
    container_name: api
    build: .
    ports:
      - "3333:3333"
    entrypoint: "./api-entrypoint.sh"
    depends_on:
      - db