name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/dependency-review-action@v1

  dast:
    runs-on: ubuntu-latest
    name: DAST
    steps:
      - uses: owasp/zap-action@v3