name: Docker Compose Workflow

on:
  push:
    branches:
      - main # você pode ajustar a branch aqui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
          docker-compose --version

      - name: Construir e Executar Docker Compose
        run: |
          docker-compose up -d --build
        working-directory: ./ # ajuste o caminho para o seu arquivo docker-compose.yml

      - name: Verificar status dos containers
        run: |
          docker ps -a
