name: Run test suite
on: [push]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: postgres:latest
      volumes: -my-app:/app
    steps:
      - name: Testes
        run: |
          cd /app
          yarn test
